/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.util.Date;
import javax.swing.JOptionPane;
import backend.LibrarianRole;
import java.time.LocalDate;
import javax.swing.JFrame;

public class BorrowBook extends javax.swing.JFrame implements Node {

    /**
     * Creates new form BorrowBook
     */
    public BorrowBook(LibrarianRole librarian) {
        initComponents();
        this.librarian = librarian;
    }

    private Node parent;
    LibrarianRole librarian;

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override

    public void setParentNode(Node node) {
        this.parent = node;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentIDTextField = new javax.swing.JTextField();
        BookIDTextField = new javax.swing.JTextField();
        BorrowButton = new javax.swing.JButton();
        StudentID = new javax.swing.JLabel();
        BorrowDate = new javax.swing.JLabel();
        BookID = new javax.swing.JLabel();
        BorrowDateInput = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        StudentIDTextField.setOpaque(true);
        StudentIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTextFieldActionPerformed(evt);
            }
        });

        BookIDTextField.setOpaque(true);
        BookIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDTextFieldActionPerformed(evt);
            }
        });

        BorrowButton.setBackground(new java.awt.Color(0, 0, 0));
        BorrowButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BorrowButton.setForeground(new java.awt.Color(255, 255, 255));
        BorrowButton.setText("Borrow");
        BorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowButtonActionPerformed(evt);
            }
        });

        StudentID.setBackground(new java.awt.Color(204, 255, 204));
        StudentID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StudentID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentID.setText("Student ID");
        StudentID.setOpaque(true);

        BorrowDate.setBackground(new java.awt.Color(204, 255, 204));
        BorrowDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BorrowDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BorrowDate.setText("Borrow Date");
        BorrowDate.setOpaque(true);

        BookID.setBackground(new java.awt.Color(204, 255, 204));
        BookID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BookID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookID.setText("Book ID");
        BookID.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BookIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(BorrowDateInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(BorrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(StudentIDTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BorrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(BookIDTextField)
                    .addComponent(BookID, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BorrowDate, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(BorrowDateInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDTextFieldActionPerformed

    private void BookIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDTextFieldActionPerformed
    public LocalDate convertToLocalDate(Date dateToConvert) {
        return new java.sql.Date(dateToConvert.getTime()).toLocalDate();
    }
    private void BorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowButtonActionPerformed
        // TODO add your handling code here:

        String bStudentID = StudentIDTextField.getText();
        String bBookID = BookIDTextField.getText();
        Date bBorrowDate = BorrowDateInput.getDate();
        int checkStatus;

        if (bStudentID.equals("") || bBookID.equals("") || bBorrowDate == null) {
            JOptionPane.showMessageDialog(null, "Some fields are empty!");
        } else {
            try{
            checkStatus = librarian.borrowBook(bStudentID, bBookID, convertToLocalDate(bBorrowDate));
            switch (checkStatus) {
                case 1:
                    JOptionPane.showMessageDialog(null, " The student with Id = " + bStudentID + " has already borrowed a copy of the book with ID = " + bBookID + " and hasn't returned it yet.");
                    break;
                case 2:
                    StudentIDTextField.setText("");
                    BookIDTextField.setText("");
                    BorrowDateInput.setDate(null);
                    JOptionPane.showMessageDialog(null, " The student with ID =  " + bStudentID + " has successfully borrowed a copy of the book with ID = " + bBookID);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, " All copies of the book with ID = " + bBookID + " have been borrowed and no copy is left for the student with ID = " + bStudentID);
                    StudentIDTextField.setText("");
                    BookIDTextField.setText("");
                    BorrowDateInput.setDate(null);
                    break;
                default:
                    break;
            }
            }catch (NullPointerException e){
                JOptionPane.showMessageDialog(null, " This book doesn't exist in the database");
                
            }

        }

    }//GEN-LAST:event_BorrowButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookID;
    private javax.swing.JTextField BookIDTextField;
    private javax.swing.JButton BorrowButton;
    private javax.swing.JLabel BorrowDate;
    private com.toedter.calendar.JDateChooser BorrowDateInput;
    private javax.swing.JLabel StudentID;
    private javax.swing.JTextField StudentIDTextField;
    // End of variables declaration//GEN-END:variables
}
