/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.StudentBook;
import backend.LibrarianRole;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ReturnBook extends javax.swing.JFrame implements Node {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook(LibrarianRole librarian) {
        initComponents();
        this.librarian = librarian;
    }

    LibrarianRole librarian;
    private Node parent;

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentIDTextField = new javax.swing.JTextField();
        ReturnButton = new javax.swing.JButton();
        StudentID = new javax.swing.JLabel();
        BookID = new javax.swing.JLabel();
        ReturnDate = new javax.swing.JLabel();
        BookIDTextField = new javax.swing.JTextField();
        ReturnDateInput = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        StudentIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StudentIDTextField.setOpaque(true);
        StudentIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTextFieldActionPerformed(evt);
            }
        });

        ReturnButton.setBackground(new java.awt.Color(0, 0, 0));
        ReturnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReturnButton.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButton.setText("Return");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        StudentID.setBackground(new java.awt.Color(204, 255, 204));
        StudentID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StudentID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentID.setText("Student ID");
        StudentID.setOpaque(true);

        BookID.setBackground(new java.awt.Color(204, 255, 204));
        BookID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BookID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookID.setText("Book ID");
        BookID.setOpaque(true);

        ReturnDate.setBackground(new java.awt.Color(204, 255, 204));
        ReturnDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReturnDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnDate.setText("Return Date");
        ReturnDate.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(ReturnDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BookID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(BookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(BookIDTextField)
                    .addComponent(BookID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(ReturnDateInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public LocalDate convertToLocalDate(Date dateToConvert) {
        return new java.sql.Date(dateToConvert.getTime()).toLocalDate();
    }
    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        String bStudentID = StudentIDTextField.getText();
        String bBookID = BookIDTextField.getText();
        Date bReturnDate = ReturnDateInput.getDate();
        double checkStatus;

        if (bStudentID.equals("")|| bBookID.equals("")|| bReturnDate == null) {
            JOptionPane.showMessageDialog(null, "Some fields are empty!");
            return;
        }
        int oldOperation = librarian.getListOfBorrowingOperations().length;

        try {
            checkStatus = librarian.returnBook(bStudentID, bBookID, convertToLocalDate(bReturnDate));
            if (oldOperation == librarian.getListOfBorrowingOperations().length){
                JOptionPane.showMessageDialog(null, " Currently no borrowing operation is occuring by this student for this book");
                StudentIDTextField.setText("");
                BookIDTextField.setText("");
                ReturnDateInput.setDate(null);
                return;
            }
            StudentIDTextField.setText("");
            BookIDTextField.setText("");
            ReturnDateInput.setDate(null);
            JOptionPane.showMessageDialog(null, " The student with id = " + bStudentID + " should pay a return fee of " + checkStatus + " US dollars for the book with id " + bBookID);

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, " Currently no borrowing operation is occuring by this student for this book");
            StudentIDTextField.setText("");
            BookIDTextField.setText("");
            ReturnDateInput.setDate(null);
        }

    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void StudentIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookID;
    private javax.swing.JTextField BookIDTextField;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel ReturnDate;
    private com.toedter.calendar.JDateChooser ReturnDateInput;
    private javax.swing.JLabel StudentID;
    private javax.swing.JTextField StudentIDTextField;
    // End of variables declaration//GEN-END:variables
}
